# This is a basic workflow to help you get started with Actions#
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     
      - uses: actions/checkout@v3
      - name: Compile Program
      # Runs a single command using the runners shell
        run: g++ helloworld.cpp -o helloworld
      # Runs a set of commands using the runners shell
      - uses: actions/upload-artifact@v3
        with:
          name: compiled-binary
          path: .
      - name: Run multiple commands
     
        run: |
          echo 1
          sleep 10
          echo 2
          echo 3

  unit-tests:
    runs-on: self-hosted
    steps:
      
      - uses: actions/checkout@v3
      - name: Run Unittests
      
        run: |
          echo "Showing source code"
          cat helloworld.cpp
          sleep 3
          echo "Showing hexdump of Binary"
          hexdump -C helloworld

  lint-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Linttests
     
        run: ./tests.sh

  deploy:
    runs-on: self-hosted
    steps:
      
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: compiled-binary
      - name: Deployment 
      
        run: |
          ls -a
          time ./helloworld
          echo "Application successfully deployed."

