# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Compile Program
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      
        run: g++ helloworld.cpp -o helloworld
      # Runs a set of commands using the runners shell
      - name: Run multiple commands
      - uses: actions/checkout@v3
        run: |
          echo 1
          echo 2
          echo 3

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      
      
      - name: Run Unittests
      - uses: actions/checkout@v3
        run: |
          echo "Showing source code"
          cat helloworld.cpp
          sleep 3
          echo "Showing hexdump of Binary"
          hexdump -C helloworld

  lint-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Linttests
      - uses: actions/checkout@v3
        run: ./tests.sh

  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Deployment
      - uses: actions/checkout@v3
        run: |
          ls -a
          time ./helloworld
          echo "Application successfully deployed."

